// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/permission/add": {
            "post": {
                "description": "批量添加权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "批量添加权限",
                "parameters": [
                    {
                        "description": "权限列表",
                        "name": "permissions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddPermissionRequestDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/auth/permission/assign": {
            "post": {
                "description": "给指定角色分配权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "给指定角色分配权限",
                "parameters": [
                    {
                        "description": "权限列表",
                        "name": "permissions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddPermissionToRoleRequestDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/auth/role/add_role_to_user": {
            "post": {
                "description": "给指定用户添加角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "给指定用户添加角色",
                "parameters": [
                    {
                        "description": "给指定用户添加角色",
                        "name": "addRoleToUserRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddRoleToUserRequestDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/auth/role/create": {
            "post": {
                "description": "创建角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "角色信息",
                        "name": "roleRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RoleRequestDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/auth/user/List": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "获取所有用户列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/user/delete": {
            "delete": {
                "tags": [
                    "用户模块"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户uuid",
                        "name": "uuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/user/logout": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/user/query_by_phone": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "根据手机号查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/user/query_by_username": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "根据用户名查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/user/query_by_uuid": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "根据uuid查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户uuid",
                        "name": "uuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/captcha/rotate/check": {
            "post": {
                "description": "验证旋转验证码",
                "tags": [
                    "旋转验证码"
                ],
                "summary": "验证旋转验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码角度",
                        "name": "angle",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/captcha/rotate/get": {
            "get": {
                "description": "生成旋转验证码",
                "tags": [
                    "旋转验证码"
                ],
                "summary": "生成旋转验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/captcha/shape/check": {
            "get": {
                "description": "生成点击形状基础验证码",
                "tags": [
                    "点击形状验证码"
                ],
                "summary": "生成点击形状基础验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/captcha/shape/get": {
            "get": {
                "description": "生成点击形状验证码",
                "tags": [
                    "点击形状验证码"
                ],
                "summary": "生成点击形状验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/captcha/shape/slide/check": {
            "get": {
                "description": "验证点击形状验证码",
                "tags": [
                    "点击形状验证码"
                ],
                "summary": "验证点击形状验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "点击坐标",
                        "name": "point",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/captcha/shape/slide/region/get": {
            "get": {
                "description": "生成点击形状验证码",
                "tags": [
                    "点击形状验证码"
                ],
                "summary": "生成点击形状验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/captcha/text/check": {
            "get": {
                "description": "验证基础文字验证码",
                "tags": [
                    "基础文字验证码"
                ],
                "summary": "验证基础文字验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "captcha",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/captcha/text/get": {
            "get": {
                "description": "生成基础文字验证码",
                "tags": [
                    "基础文字验证码"
                ],
                "summary": "生成基础文字验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码类型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/comment/reply": {
            "post": {
                "description": "提交回复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "提交回复",
                "parameters": [
                    {
                        "description": "回复评论请求",
                        "name": "reply_comment_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReplyCommentRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/comment/submit": {
            "post": {
                "description": "提交评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "提交评论",
                "parameters": [
                    {
                        "description": "评论请求",
                        "name": "comment_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CommentRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/oauth/callback_notify": {
            "post": {
                "description": "微信回调",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信公众号"
                ],
                "summary": "微信回调",
                "responses": {}
            }
        },
        "/api/oauth/callback_verify": {
            "get": {
                "description": "微信回调验证",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信公众号"
                ],
                "summary": "微信回调验证",
                "responses": {}
            }
        },
        "/api/oauth/generate_client_id": {
            "get": {
                "description": "生成客户端ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信公众号"
                ],
                "summary": "生成客户端ID",
                "responses": {}
            }
        },
        "/api/oauth/get_temp_qrcode": {
            "get": {
                "description": "获取临时二维码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信公众号"
                ],
                "summary": "获取临时二维码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/oauth/gitee/callback": {
            "get": {
                "description": "处理Gitee回调",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitee OAuth"
                ],
                "summary": "处理Gitee回调",
                "responses": {}
            }
        },
        "/api/oauth/gitee/get_url": {
            "get": {
                "description": "获取Gitee登录地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitee OAuth"
                ],
                "summary": "获取Gitee登录地址",
                "responses": {
                    "200": {
                        "description": "登录地址",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/oauth/github/callback": {
            "get": {
                "description": "登录回调函数",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Github OAuth"
                ],
                "summary": "登录回调函数",
                "parameters": [
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/oauth/github/get_url": {
            "get": {
                "description": "获取github登录url",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Github OAuth"
                ],
                "summary": "获取github登录url",
                "responses": {
                    "200": {
                        "description": "登录url",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/oauth/qq/callback": {
            "get": {
                "description": "QQ登录回调",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QQ OAuth"
                ],
                "summary": "QQ登录回调",
                "responses": {}
            }
        },
        "/api/oauth/qq/get_url": {
            "get": {
                "description": "获取QQ登录地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QQ OAuth"
                ],
                "summary": "获取QQ登录地址",
                "responses": {
                    "200": {
                        "description": "登录地址",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/sms/ali/send": {
            "get": {
                "description": "发送短信验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短信验证码"
                ],
                "summary": "发送短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/sms/smsbao/send": {
            "get": {
                "description": "短信宝发送短信验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短信验证码"
                ],
                "summary": "短信宝发送短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/sms/test/send": {
            "get": {
                "description": "发送测试短信验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短信验证码"
                ],
                "summary": "发送测试短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/token/refresh": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "刷新token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "刷新token",
                        "name": "refresh_token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "账号登录",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AccountLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/phone_login": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "手机号登录/注册",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PhoneLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/reset_password": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/ws/gws": {
            "get": {
                "description": "创建websocket服务",
                "tags": [
                    "websocket"
                ],
                "summary": "创建websocket服务",
                "responses": {}
            }
        }
    },
    "definitions": {
        "dto.AccountLoginRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "auto_login": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.AddPermissionRequestDto": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ScaAuthPermission"
                    }
                }
            }
        },
        "dto.AddPermissionToRoleRequestDto": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "role_key": {
                    "type": "string"
                }
            }
        },
        "dto.AddRoleToUserRequestDto": {
            "type": "object",
            "properties": {
                "role_key": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "dto.CommentRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "topic_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.PhoneLoginRequest": {
            "type": "object",
            "properties": {
                "auto_login": {
                    "type": "boolean"
                },
                "captcha": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.ReplyCommentRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reply_id": {
                    "type": "string"
                },
                "reply_user": {
                    "type": "string"
                },
                "topic_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordRequest": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "repassword": {
                    "type": "string"
                }
            }
        },
        "dto.RoleRequestDto": {
            "type": "object",
            "properties": {
                "role_key": {
                    "type": "string"
                },
                "role_name": {
                    "type": "string"
                }
            }
        },
        "model.ScaAuthPermission": {
            "type": "object",
            "properties": {
                "created_by": {
                    "description": "创建人",
                    "type": "string"
                },
                "created_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "deleted": {
                    "description": "是否删除",
                    "type": "integer"
                },
                "icon": {
                    "description": "图标",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "method": {
                    "description": "请求方式",
                    "type": "string"
                },
                "order": {
                    "description": "排序",
                    "type": "integer"
                },
                "parent_id": {
                    "description": "父ID",
                    "type": "integer"
                },
                "path": {
                    "description": "路径",
                    "type": "string"
                },
                "permission_key": {
                    "description": "权限关键字",
                    "type": "string"
                },
                "permission_name": {
                    "description": "权限名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注 描述",
                    "type": "string"
                },
                "status": {
                    "description": "状态 0 启用 1 停用",
                    "type": "integer"
                },
                "type": {
                    "description": "类型 0 菜单 1 目录 2 按钮 -1其他",
                    "type": "integer"
                },
                "update_by": {
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
