// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/controller/auth/permission/add": {
            "post": {
                "description": "批量添加权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "批量添加权限",
                "parameters": [
                    {
                        "description": "权限列表",
                        "name": "permissions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/permission_controller.AddPermissionRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/controller/auth/permission/assign": {
            "post": {
                "description": "给指定角色分配权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "给指定角色分配权限",
                "parameters": [
                    {
                        "description": "权限列表",
                        "name": "permissions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/permission_controller.AddPermissionToRoleRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/controller/auth/role/add_role_to_user": {
            "post": {
                "description": "给指定用户添加角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "给指定用户添加角色",
                "parameters": [
                    {
                        "description": "给指定用户添加角色",
                        "name": "addRoleToUserRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_controller.AddRoleToUserRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/controller/auth/role/create": {
            "post": {
                "description": "创建角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "角色信息",
                        "name": "roleRequestDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_controller.RoleRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/controller/auth/user/List": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "获取所有用户列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/auth/user/delete": {
            "delete": {
                "tags": [
                    "用户模块"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户uuid",
                        "name": "uuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/auth/user/logout": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/auth/user/query_by_phone": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "根据手机号查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/auth/user/query_by_username": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "根据用户名查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/auth/user/query_by_uuid": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "根据uuid查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户uuid",
                        "name": "uuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/captcha/rotate/check": {
            "post": {
                "description": "验证旋转验证码",
                "tags": [
                    "旋转验证码"
                ],
                "summary": "验证旋转验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码角度",
                        "name": "angle",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/captcha/rotate/get": {
            "get": {
                "description": "生成旋转验证码",
                "tags": [
                    "旋转验证码"
                ],
                "summary": "生成旋转验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/captcha/shape/get": {
            "get": {
                "description": "生成点击形状验证码",
                "tags": [
                    "点击形状验证码"
                ],
                "summary": "生成点击形状验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/captcha/shape/slide/check": {
            "get": {
                "description": "验证滑动验证码",
                "tags": [
                    "验证滑动验证码"
                ],
                "summary": "验证滑动验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "点击坐标",
                        "name": "point",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/captcha/shape/slide/region/get": {
            "get": {
                "description": "生成滑动区域形状验证码",
                "tags": [
                    "生成滑动区域形状验证码"
                ],
                "summary": "生成滑动区域形状验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/captcha/slide/generate": {
            "get": {
                "description": "滑块基础验证码",
                "tags": [
                    "滑块基础验证码"
                ],
                "summary": "滑块基础验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/captcha/text/check": {
            "get": {
                "description": "验证基础文字验证码",
                "tags": [
                    "基础文字验证码"
                ],
                "summary": "验证基础文字验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "captcha",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/captcha/text/get": {
            "get": {
                "description": "生成基础文字验证码",
                "tags": [
                    "基础文字验证码"
                ],
                "summary": "生成基础文字验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码类型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/oauth/callback_notify": {
            "post": {
                "description": "微信回调",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信公众号"
                ],
                "summary": "微信回调",
                "responses": {}
            }
        },
        "/controller/oauth/callback_verify": {
            "get": {
                "description": "微信回调验证",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信公众号"
                ],
                "summary": "微信回调验证",
                "responses": {}
            }
        },
        "/controller/oauth/generate_client_id": {
            "get": {
                "description": "生成客户端ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信公众号"
                ],
                "summary": "生成客户端ID",
                "responses": {}
            }
        },
        "/controller/oauth/get_temp_qrcode": {
            "get": {
                "description": "获取临时二维码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信公众号"
                ],
                "summary": "获取临时二维码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/controller/oauth/gitee/callback": {
            "get": {
                "description": "处理Gitee回调",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitee OAuth"
                ],
                "summary": "处理Gitee回调",
                "responses": {}
            }
        },
        "/controller/oauth/gitee/get_url": {
            "get": {
                "description": "获取Gitee登录地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitee OAuth"
                ],
                "summary": "获取Gitee登录地址",
                "responses": {
                    "200": {
                        "description": "登录地址",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/oauth/github/callback": {
            "get": {
                "description": "登录回调函数",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Github OAuth"
                ],
                "summary": "登录回调函数",
                "parameters": [
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/oauth/github/get_url": {
            "get": {
                "description": "获取github登录url",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Github OAuth"
                ],
                "summary": "获取github登录url",
                "responses": {
                    "200": {
                        "description": "登录url",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/oauth/qq/callback": {
            "get": {
                "description": "QQ登录回调",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QQ OAuth"
                ],
                "summary": "QQ登录回调",
                "responses": {}
            }
        },
        "/controller/oauth/qq/get_url": {
            "get": {
                "description": "获取QQ登录地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "QQ OAuth"
                ],
                "summary": "获取QQ登录地址",
                "responses": {
                    "200": {
                        "description": "登录地址",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/sms/ali/send": {
            "get": {
                "description": "发送短信验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短信验证码"
                ],
                "summary": "发送短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/controller/sms/smsbao/send": {
            "post": {
                "description": "短信宝发送短信验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短信验证码"
                ],
                "summary": "短信宝发送短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/controller/sms/test/send": {
            "post": {
                "description": "发送测试短信验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短信验证码"
                ],
                "summary": "发送测试短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/controller/token/refresh": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "刷新token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "刷新token",
                        "name": "refresh_token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/user/login": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "账号登录",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_controller.AccountLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/user/phone_login": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "手机号登录/注册",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_controller.PhoneLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/user/reset_password": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_controller.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/controller/ws/gws": {
            "get": {
                "description": "创建websocket服务",
                "tags": [
                    "websocket"
                ],
                "summary": "创建websocket服务",
                "responses": {}
            }
        },
        "/auth/comment/cancel_like": {
            "post": {
                "description": "取消点赞评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "取消点赞评论",
                "parameters": [
                    {
                        "description": "取消点赞请求",
                        "name": "comment_like_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment_controller.CommentLikeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/comment/like": {
            "post": {
                "description": "点赞评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "点赞评论",
                "parameters": [
                    {
                        "description": "点赞请求",
                        "name": "comment_like_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment_controller.CommentLikeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/comment/list": {
            "post": {
                "description": "获取评论列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "获取评论列表",
                "parameters": [
                    {
                        "description": "评论列表请求",
                        "name": "comment_list_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment_controller.CommentListRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/comment/submit": {
            "post": {
                "description": "提交评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "提交评论",
                "parameters": [
                    {
                        "description": "评论请求",
                        "name": "comment_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment_controller.CommentRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/reply/list": {
            "post": {
                "description": "获取回复列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "获取回复列表",
                "parameters": [
                    {
                        "description": "回复列表请求",
                        "name": "reply_list_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment_controller.ReplyListRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/reply/reply/submit": {
            "post": {
                "description": "提交回复的回复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "提交回复的回复",
                "parameters": [
                    {
                        "description": "回复回复请求",
                        "name": "reply_reply_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment_controller.ReplyReplyRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/reply/submit": {
            "post": {
                "description": "提交回复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "提交回复",
                "parameters": [
                    {
                        "description": "回复评论请求",
                        "name": "reply_comment_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment_controller.ReplyCommentRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "comment_controller.CommentLikeRequest": {
            "type": "object",
            "required": [
                "comment_id",
                "topic_id",
                "user_id"
            ],
            "properties": {
                "comment_id": {
                    "type": "integer"
                },
                "topic_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "comment_controller.CommentListRequest": {
            "type": "object",
            "required": [
                "topic_id",
                "user_id"
            ],
            "properties": {
                "is_hot": {
                    "type": "boolean",
                    "default": true
                },
                "page": {
                    "type": "integer",
                    "default": 1
                },
                "size": {
                    "type": "integer",
                    "default": 5
                },
                "topic_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "comment_controller.CommentRequest": {
            "type": "object",
            "required": [
                "author",
                "content",
                "key",
                "point",
                "topic_id",
                "user_id"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "key": {
                    "type": "string"
                },
                "point": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "topic_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "comment_controller.ReplyCommentRequest": {
            "type": "object",
            "required": [
                "author",
                "content",
                "key",
                "point",
                "reply_id",
                "reply_user",
                "topic_id",
                "user_id"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "key": {
                    "type": "string"
                },
                "point": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "reply_id": {
                    "type": "integer"
                },
                "reply_user": {
                    "type": "string"
                },
                "topic_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "comment_controller.ReplyListRequest": {
            "type": "object",
            "required": [
                "comment_id",
                "topic_id",
                "user_id"
            ],
            "properties": {
                "comment_id": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer",
                    "default": 1
                },
                "size": {
                    "type": "integer",
                    "default": 5
                },
                "topic_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "comment_controller.ReplyReplyRequest": {
            "type": "object",
            "required": [
                "author",
                "content",
                "key",
                "point",
                "reply_id",
                "reply_to",
                "reply_user",
                "topic_id",
                "user_id"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "key": {
                    "type": "string"
                },
                "point": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "reply_id": {
                    "type": "integer"
                },
                "reply_to": {
                    "type": "integer"
                },
                "reply_user": {
                    "type": "string"
                },
                "topic_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.ScaAuthPermission": {
            "type": "object",
            "properties": {
                "created_by": {
                    "description": "创建人",
                    "type": "string"
                },
                "created_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "deleted": {
                    "description": "是否删除",
                    "type": "integer"
                },
                "icon": {
                    "description": "图标",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "method": {
                    "description": "请求方式",
                    "type": "string"
                },
                "order": {
                    "description": "排序",
                    "type": "integer"
                },
                "parent_id": {
                    "description": "父ID",
                    "type": "integer"
                },
                "path": {
                    "description": "路径",
                    "type": "string"
                },
                "permission_key": {
                    "description": "权限关键字",
                    "type": "string"
                },
                "permission_name": {
                    "description": "权限名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注 描述",
                    "type": "string"
                },
                "status": {
                    "description": "状态 0 启用 1 停用",
                    "type": "integer"
                },
                "type": {
                    "description": "类型 0 菜单 1 目录 2 按钮 -1其他",
                    "type": "integer"
                },
                "update_by": {
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "permission_controller.AddPermissionRequest": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ScaAuthPermission"
                    }
                }
            }
        },
        "permission_controller.AddPermissionToRoleRequest": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "role_key": {
                    "type": "string"
                }
            }
        },
        "role_controller.AddRoleToUserRequest": {
            "type": "object",
            "required": [
                "role_key",
                "uid"
            ],
            "properties": {
                "role_key": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "role_controller.RoleRequest": {
            "type": "object",
            "required": [
                "role_key",
                "role_name"
            ],
            "properties": {
                "role_key": {
                    "type": "string"
                },
                "role_name": {
                    "type": "string"
                }
            }
        },
        "user_controller.AccountLoginRequest": {
            "type": "object",
            "required": [
                "account",
                "angle",
                "auto_login",
                "key",
                "password"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "angle": {
                    "type": "integer"
                },
                "auto_login": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user_controller.PhoneLoginRequest": {
            "type": "object",
            "required": [
                "auto_login",
                "captcha",
                "phone"
            ],
            "properties": {
                "auto_login": {
                    "type": "boolean"
                },
                "captcha": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "user_controller.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "captcha",
                "password",
                "phone",
                "repassword"
            ],
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "repassword": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
