definitions:
  dto.AccountLoginRequest:
    properties:
      account:
        type: string
      password:
        type: string
    type: object
  dto.AddUserRequest:
    properties:
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/user/List:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取所有用户列表
      tags:
      - 鉴权模块
  /api/auth/user/delete:
    delete:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除用户
      tags:
      - 鉴权模块
  /api/auth/user/query_by_phone:
    get:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据手机号查询用户
      tags:
      - 鉴权模块
  /api/auth/user/query_by_username:
    get:
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据用户名查询用户
      tags:
      - 鉴权模块
  /api/auth/user/query_by_uuid:
    get:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据uuid查询用户
      tags:
      - 鉴权模块
  /api/captcha/rotate/check:
    post:
      description: 验证旋转验证码
      parameters:
      - description: 验证码角度
        in: query
        name: angle
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/rotate/get:
    get:
      description: 生成旋转验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/shape/check:
    get:
      description: 验证点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/get:
    get:
      description: 生成点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/check:
    get:
      description: 验证点击形状验证码
      parameters:
      - description: 点击坐标
        in: query
        name: point
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/region/get:
    get:
      description: 验证点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/text/check:
    get:
      description: 验证基础文字验证码
      parameters:
      - description: 验证码
        in: query
        name: captcha
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证基础文字验证码
      tags:
      - 基础文字验证码
  /api/captcha/text/get:
    get:
      description: 生成基础文字验证码
      parameters:
      - description: 验证码类型
        in: query
        name: type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成基础文字验证码
      tags:
      - 基础文字验证码
  /api/sms/ali/send:
    get:
      description: 发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送短信验证码
      tags:
      - 短信验证码
  /api/sms/smsbao/send:
    get:
      description: 发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 短信宝发送短信验证码
      tags:
      - 短信验证码
  /api/sms/test/send:
    get:
      description: 发送测试短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送测试短信验证码
      tags:
      - 短信验证码
  /api/token/refresh:
    post:
      parameters:
      - description: 刷新token
        in: query
        name: refresh_token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 刷新token
      tags:
      - 鉴权模块
  /api/user/add:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AddUserRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 添加用户
      tags:
      - 鉴权模块
  /api/user/login:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AccountLoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 账号登录
      tags:
      - 鉴权模块
  /api/user/phone_login:
    post:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 验证码
        in: query
        name: captcha
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 手机号登录/注册
      tags:
      - 鉴权模块
swagger: "2.0"
