definitions:
  comment_api.CommentLikeRequest:
    properties:
      comment_id:
        type: integer
      topic_id:
        type: string
      user_id:
        type: string
    required:
    - comment_id
    - topic_id
    - user_id
    type: object
  comment_api.CommentListRequest:
    properties:
      is_hot:
        default: true
        type: boolean
      page:
        default: 1
        type: integer
      size:
        default: 5
        type: integer
      topic_id:
        type: string
      user_id:
        type: string
    required:
    - topic_id
    - user_id
    type: object
  comment_api.CommentRequest:
    properties:
      author:
        type: string
      content:
        type: string
      images:
        items:
          type: string
        type: array
      key:
        type: string
      point:
        items:
          type: integer
        type: array
      topic_id:
        type: string
      user_id:
        type: string
    required:
    - author
    - content
    - key
    - point
    - topic_id
    - user_id
    type: object
  comment_api.ReplyCommentRequest:
    properties:
      author:
        type: string
      content:
        type: string
      images:
        items:
          type: string
        type: array
      key:
        type: string
      point:
        items:
          type: integer
        type: array
      reply_id:
        type: integer
      reply_user:
        type: string
      topic_id:
        type: string
      user_id:
        type: string
    required:
    - author
    - content
    - key
    - point
    - reply_id
    - reply_user
    - topic_id
    - user_id
    type: object
  comment_api.ReplyListRequest:
    properties:
      comment_id:
        type: integer
      page:
        default: 1
        type: integer
      size:
        default: 5
        type: integer
      topic_id:
        type: string
      user_id:
        type: string
    required:
    - comment_id
    - topic_id
    - user_id
    type: object
  comment_api.ReplyReplyRequest:
    properties:
      author:
        type: string
      content:
        type: string
      images:
        items:
          type: string
        type: array
      key:
        type: string
      point:
        items:
          type: integer
        type: array
      reply_id:
        type: integer
      reply_to:
        type: integer
      reply_user:
        type: string
      topic_id:
        type: string
      user_id:
        type: string
    required:
    - author
    - content
    - key
    - point
    - reply_id
    - reply_to
    - reply_user
    - topic_id
    - user_id
    type: object
  model.ScaAuthPermission:
    properties:
      created_by:
        description: 创建人
        type: string
      created_time:
        description: 创建时间
        type: string
      deleted:
        description: 是否删除
        type: integer
      icon:
        description: 图标
        type: string
      id:
        description: 主键ID
        type: integer
      method:
        description: 请求方式
        type: string
      order:
        description: 排序
        type: integer
      parent_id:
        description: 父ID
        type: integer
      path:
        description: 路径
        type: string
      permission_key:
        description: 权限关键字
        type: string
      permission_name:
        description: 权限名称
        type: string
      remark:
        description: 备注 描述
        type: string
      status:
        description: 状态 0 启用 1 停用
        type: integer
      type:
        description: 类型 0 菜单 1 目录 2 按钮 -1其他
        type: integer
      update_by:
        type: string
      update_time:
        description: 更新时间
        type: string
    type: object
  permission_api.AddPermissionRequest:
    properties:
      permissions:
        items:
          $ref: '#/definitions/model.ScaAuthPermission'
        type: array
    type: object
  permission_api.AddPermissionToRoleRequest:
    properties:
      method:
        type: string
      permission:
        type: string
      role_key:
        type: string
    type: object
  role_api.AddRoleToUserRequest:
    properties:
      role_key:
        type: string
      uid:
        type: string
    required:
    - role_key
    - uid
    type: object
  role_api.RoleRequest:
    properties:
      role_key:
        type: string
      role_name:
        type: string
    required:
    - role_key
    - role_name
    type: object
  user_api.AccountLoginRequest:
    properties:
      account:
        type: string
      angle:
        type: integer
      auto_login:
        type: boolean
      key:
        type: string
      password:
        type: string
    required:
    - account
    - angle
    - auto_login
    - key
    - password
    type: object
  user_api.PhoneLoginRequest:
    properties:
      auto_login:
        type: boolean
      captcha:
        type: string
      phone:
        type: string
    required:
    - auto_login
    - captcha
    - phone
    type: object
  user_api.ResetPasswordRequest:
    properties:
      captcha:
        type: string
      password:
        type: string
      phone:
        type: string
      repassword:
        type: string
    required:
    - captcha
    - password
    - phone
    - repassword
    type: object
info:
  contact: {}
paths:
  /api/auth/permission/add:
    post:
      consumes:
      - application/json
      description: 批量添加权限
      parameters:
      - description: 权限列表
        in: body
        name: permissions
        required: true
        schema:
          $ref: '#/definitions/permission_api.AddPermissionRequest'
      produces:
      - application/json
      responses: {}
      summary: 批量添加权限
      tags:
      - 权限管理
  /api/auth/permission/assign:
    post:
      consumes:
      - application/json
      description: 给指定角色分配权限
      parameters:
      - description: 权限列表
        in: body
        name: permissions
        required: true
        schema:
          $ref: '#/definitions/permission_api.AddPermissionToRoleRequest'
      produces:
      - application/json
      responses: {}
      summary: 给指定角色分配权限
      tags:
      - 权限管理
  /api/auth/role/add_role_to_user:
    post:
      consumes:
      - application/json
      description: 给指定用户添加角色
      parameters:
      - description: 给指定用户添加角色
        in: body
        name: addRoleToUserRequestDto
        required: true
        schema:
          $ref: '#/definitions/role_api.AddRoleToUserRequest'
      produces:
      - application/json
      responses: {}
      summary: 给指定用户添加角色
      tags:
      - 角色
  /api/auth/role/create:
    post:
      consumes:
      - application/json
      description: 创建角色
      parameters:
      - description: 角色信息
        in: body
        name: roleRequestDto
        required: true
        schema:
          $ref: '#/definitions/role_api.RoleRequest'
      produces:
      - application/json
      responses: {}
      summary: 创建角色
      tags:
      - 角色
  /api/auth/user/List:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取所有用户列表
      tags:
      - 用户模块
  /api/auth/user/delete:
    delete:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
  /api/auth/user/logout:
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 退出登录
      tags:
      - 用户模块
  /api/auth/user/query_by_phone:
    get:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据手机号查询用户
      tags:
      - 用户模块
  /api/auth/user/query_by_username:
    get:
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据用户名查询用户
      tags:
      - 用户模块
  /api/auth/user/query_by_uuid:
    get:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据uuid查询用户
      tags:
      - 用户模块
  /api/captcha/rotate/check:
    post:
      description: 验证旋转验证码
      parameters:
      - description: 验证码角度
        in: query
        name: angle
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/rotate/get:
    get:
      description: 生成旋转验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/shape/get:
    get:
      description: 生成点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/check:
    get:
      description: 验证滑动验证码
      parameters:
      - description: 点击坐标
        in: query
        name: point
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证滑动验证码
      tags:
      - 验证滑动验证码
  /api/captcha/shape/slide/region/get:
    get:
      description: 生成滑动区域形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成滑动区域形状验证码
      tags:
      - 生成滑动区域形状验证码
  /api/captcha/slide/generate:
    get:
      description: 滑块基础验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 滑块基础验证码
      tags:
      - 滑块基础验证码
  /api/captcha/text/check:
    get:
      description: 验证基础文字验证码
      parameters:
      - description: 验证码
        in: query
        name: captcha
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证基础文字验证码
      tags:
      - 基础文字验证码
  /api/captcha/text/get:
    get:
      description: 生成基础文字验证码
      parameters:
      - description: 验证码类型
        in: query
        name: type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成基础文字验证码
      tags:
      - 基础文字验证码
  /api/oauth/callback_notify:
    post:
      description: 微信回调
      produces:
      - application/json
      responses: {}
      summary: 微信回调
      tags:
      - 微信公众号
  /api/oauth/callback_verify:
    get:
      description: 微信回调验证
      produces:
      - application/json
      responses: {}
      summary: 微信回调验证
      tags:
      - 微信公众号
  /api/oauth/generate_client_id:
    get:
      description: 生成客户端ID
      produces:
      - application/json
      responses: {}
      summary: 生成客户端ID
      tags:
      - 微信公众号
  /api/oauth/get_temp_qrcode:
    get:
      description: 获取临时二维码
      parameters:
      - description: 客户端ID
        in: query
        name: client_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 获取临时二维码
      tags:
      - 微信公众号
  /api/oauth/gitee/callback:
    get:
      description: 处理Gitee回调
      produces:
      - application/json
      responses: {}
      summary: 处理Gitee回调
      tags:
      - Gitee OAuth
  /api/oauth/gitee/get_url:
    get:
      description: 获取Gitee登录地址
      produces:
      - application/json
      responses:
        "200":
          description: 登录地址
          schema:
            type: string
      summary: 获取Gitee登录地址
      tags:
      - Gitee OAuth
  /api/oauth/github/callback:
    get:
      description: 登录回调函数
      parameters:
      - description: code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            type: string
      summary: 登录回调函数
      tags:
      - Github OAuth
  /api/oauth/github/get_url:
    get:
      description: 获取github登录url
      produces:
      - application/json
      responses:
        "200":
          description: 登录url
          schema:
            type: string
      summary: 获取github登录url
      tags:
      - Github OAuth
  /api/oauth/qq/callback:
    get:
      description: QQ登录回调
      produces:
      - application/json
      responses: {}
      summary: QQ登录回调
      tags:
      - QQ OAuth
  /api/oauth/qq/get_url:
    get:
      description: 获取QQ登录地址
      produces:
      - application/json
      responses:
        "200":
          description: 登录地址
          schema:
            type: string
      summary: 获取QQ登录地址
      tags:
      - QQ OAuth
  /api/sms/ali/send:
    get:
      description: 发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送短信验证码
      tags:
      - 短信验证码
  /api/sms/smsbao/send:
    post:
      description: 短信宝发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 短信宝发送短信验证码
      tags:
      - 短信验证码
  /api/sms/test/send:
    post:
      description: 发送测试短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送测试短信验证码
      tags:
      - 短信验证码
  /api/token/refresh:
    post:
      parameters:
      - description: 刷新token
        in: query
        name: refresh_token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 刷新token
      tags:
      - 用户模块
  /api/user/login:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user_api.AccountLoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 账号登录
      tags:
      - 用户模块
  /api/user/phone_login:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user_api.PhoneLoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 手机号登录/注册
      tags:
      - 用户模块
  /api/user/reset_password:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user_api.ResetPasswordRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 重置密码
      tags:
      - 用户模块
  /api/ws/gws:
    get:
      description: 创建websocket服务
      responses: {}
      summary: 创建websocket服务
      tags:
      - websocket
  /auth/comment/cancel_like:
    post:
      consumes:
      - application/json
      description: 取消点赞评论
      parameters:
      - description: 取消点赞请求
        in: body
        name: comment_like_request
        required: true
        schema:
          $ref: '#/definitions/comment_api.CommentLikeRequest'
      produces:
      - application/json
      responses: {}
      summary: 取消点赞评论
      tags:
      - 评论
  /auth/comment/like:
    post:
      consumes:
      - application/json
      description: 点赞评论
      parameters:
      - description: 点赞请求
        in: body
        name: comment_like_request
        required: true
        schema:
          $ref: '#/definitions/comment_api.CommentLikeRequest'
      produces:
      - application/json
      responses: {}
      summary: 点赞评论
      tags:
      - 评论
  /auth/comment/list:
    post:
      consumes:
      - application/json
      description: 获取评论列表
      parameters:
      - description: 评论列表请求
        in: body
        name: comment_list_request
        required: true
        schema:
          $ref: '#/definitions/comment_api.CommentListRequest'
      produces:
      - application/json
      responses: {}
      summary: 获取评论列表
      tags:
      - 评论
  /auth/comment/submit:
    post:
      consumes:
      - application/json
      description: 提交评论
      parameters:
      - description: 评论请求
        in: body
        name: comment_request
        required: true
        schema:
          $ref: '#/definitions/comment_api.CommentRequest'
      produces:
      - application/json
      responses: {}
      summary: 提交评论
      tags:
      - 评论
  /auth/reply/list:
    post:
      consumes:
      - application/json
      description: 获取回复列表
      parameters:
      - description: 回复列表请求
        in: body
        name: reply_list_request
        required: true
        schema:
          $ref: '#/definitions/comment_api.ReplyListRequest'
      produces:
      - application/json
      responses: {}
      summary: 获取回复列表
      tags:
      - 评论
  /auth/reply/reply/submit:
    post:
      consumes:
      - application/json
      description: 提交回复的回复
      parameters:
      - description: 回复回复请求
        in: body
        name: reply_reply_request
        required: true
        schema:
          $ref: '#/definitions/comment_api.ReplyReplyRequest'
      produces:
      - application/json
      responses: {}
      summary: 提交回复的回复
      tags:
      - 评论
  /auth/reply/submit:
    post:
      consumes:
      - application/json
      description: 提交回复
      parameters:
      - description: 回复评论请求
        in: body
        name: reply_comment_request
        required: true
        schema:
          $ref: '#/definitions/comment_api.ReplyCommentRequest'
      produces:
      - application/json
      responses: {}
      summary: 提交回复
      tags:
      - 评论
swagger: "2.0"
