definitions:
  model.ScaAuthUser:
    properties:
      avatar:
        description: 头像
        type: string
      blog:
        description: 博客
        type: string
      company:
        description: 公司
        type: string
      created_by:
        description: 创建人
        type: string
      created_time:
        description: 创建时间
        type: string
      email:
        description: 邮箱
        type: string
      gender:
        description: 性别
        type: string
      introduce:
        description: 介绍
        type: string
      location:
        description: 地址
        type: string
      nickname:
        description: 昵称
        type: string
      phone:
        description: 电话
        type: string
      status:
        description: 状态 0 正常 1 封禁
        type: integer
      update_by:
        description: 更新人
        type: string
      update_time:
        description: 更新时间
        type: string
      username:
        description: 用户名
        type: string
      uuid:
        description: 唯一ID
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/user/List:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取所有用户列表
      tags:
      - 鉴权模块
  /api/auth/user/delete:
    delete:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除用户
      tags:
      - 鉴权模块
  /api/auth/user/login:
    post:
      parameters:
      - description: 账号
        in: query
        name: account
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 账号登录
      tags:
      - 鉴权模块
  /api/auth/user/query_by_phone:
    get:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据手机号查询用户
      tags:
      - 鉴权模块
  /api/auth/user/query_by_username:
    get:
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据用户名查询用户
      tags:
      - 鉴权模块
  /api/auth/user/query_by_uuid:
    get:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据uuid查询用户
      tags:
      - 鉴权模块
  /api/auth/user/register:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.ScaAuthUser'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户注册
      tags:
      - 鉴权模块
  /api/captcha/rotate/check:
    post:
      description: 验证旋转验证码
      parameters:
      - description: 验证码角度
        in: query
        name: angle
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/rotate/get:
    get:
      description: 生成旋转验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/shape/check:
    get:
      description: 验证点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/get:
    get:
      description: 生成点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/check:
    get:
      description: 验证点击形状验证码
      parameters:
      - description: 点击坐标
        in: query
        name: point
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/region/get:
    get:
      description: 验证点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/text/check:
    get:
      description: 验证基础文字验证码
      parameters:
      - description: 验证码
        in: query
        name: captcha
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证基础文字验证码
      tags:
      - 基础文字验证码
  /api/captcha/text/get:
    get:
      description: 生成基础文字验证码
      parameters:
      - description: 验证码类型
        in: query
        name: type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成基础文字验证码
      tags:
      - 基础文字验证码
  /api/sms/ali/send:
    get:
      description: 发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送短信验证码
      tags:
      - 短信验证码
  /api/sms/smsbao/send:
    get:
      description: 发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送短信验证码
      tags:
      - 短信验证码
swagger: "2.0"
