definitions:
  dto.AccountLoginRequest:
    properties:
      account:
        type: string
      auto_login:
        type: boolean
      password:
        type: string
    type: object
  dto.AddPermissionRequestDto:
    properties:
      permissions:
        items:
          $ref: '#/definitions/model.ScaAuthPermission'
        type: array
    type: object
  dto.AddPermissionToRoleRequestDto:
    properties:
      method:
        type: string
      permission:
        type: string
      role_key:
        type: string
    type: object
  dto.AddRoleToUserRequestDto:
    properties:
      role_key:
        type: string
      uid:
        type: string
    type: object
  dto.CommentRequest:
    properties:
      content:
        type: string
      images:
        items:
          type: string
        type: array
      topic_id:
        type: string
      user_id:
        type: string
    type: object
  dto.PhoneLoginRequest:
    properties:
      auto_login:
        type: boolean
      captcha:
        type: string
      phone:
        type: string
    type: object
  dto.ReplyCommentRequest:
    properties:
      content:
        type: string
      images:
        items:
          type: string
        type: array
      reply_id:
        type: string
      reply_user:
        type: string
      topic_id:
        type: string
      user_id:
        type: string
    type: object
  dto.ResetPasswordRequest:
    properties:
      captcha:
        type: string
      password:
        type: string
      phone:
        type: string
      repassword:
        type: string
    type: object
  dto.RoleRequestDto:
    properties:
      role_key:
        type: string
      role_name:
        type: string
    type: object
  model.ScaAuthPermission:
    properties:
      created_by:
        description: 创建人
        type: string
      created_time:
        description: 创建时间
        type: string
      deleted:
        description: 是否删除
        type: integer
      icon:
        description: 图标
        type: string
      id:
        description: 主键ID
        type: integer
      method:
        description: 请求方式
        type: string
      order:
        description: 排序
        type: integer
      parent_id:
        description: 父ID
        type: integer
      path:
        description: 路径
        type: string
      permission_key:
        description: 权限关键字
        type: string
      permission_name:
        description: 权限名称
        type: string
      remark:
        description: 备注 描述
        type: string
      status:
        description: 状态 0 启用 1 停用
        type: integer
      type:
        description: 类型 0 菜单 1 目录 2 按钮 -1其他
        type: integer
      update_by:
        type: string
      update_time:
        description: 更新时间
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/permission/add:
    post:
      consumes:
      - application/json
      description: 批量添加权限
      parameters:
      - description: 权限列表
        in: body
        name: permissions
        required: true
        schema:
          $ref: '#/definitions/dto.AddPermissionRequestDto'
      produces:
      - application/json
      responses: {}
      summary: 批量添加权限
      tags:
      - 权限管理
  /api/auth/permission/assign:
    post:
      consumes:
      - application/json
      description: 给指定角色分配权限
      parameters:
      - description: 权限列表
        in: body
        name: permissions
        required: true
        schema:
          $ref: '#/definitions/dto.AddPermissionToRoleRequestDto'
      produces:
      - application/json
      responses: {}
      summary: 给指定角色分配权限
      tags:
      - 权限管理
  /api/auth/role/add_role_to_user:
    post:
      consumes:
      - application/json
      description: 给指定用户添加角色
      parameters:
      - description: 给指定用户添加角色
        in: body
        name: addRoleToUserRequestDto
        required: true
        schema:
          $ref: '#/definitions/dto.AddRoleToUserRequestDto'
      produces:
      - application/json
      responses: {}
      summary: 给指定用户添加角色
      tags:
      - 角色
  /api/auth/role/create:
    post:
      consumes:
      - application/json
      description: 创建角色
      parameters:
      - description: 角色信息
        in: body
        name: roleRequestDto
        required: true
        schema:
          $ref: '#/definitions/dto.RoleRequestDto'
      produces:
      - application/json
      responses: {}
      summary: 创建角色
      tags:
      - 角色
  /api/auth/user/List:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取所有用户列表
      tags:
      - 用户模块
  /api/auth/user/delete:
    delete:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
  /api/auth/user/logout:
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 退出登录
      tags:
      - 用户模块
  /api/auth/user/query_by_phone:
    get:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据手机号查询用户
      tags:
      - 用户模块
  /api/auth/user/query_by_username:
    get:
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据用户名查询用户
      tags:
      - 用户模块
  /api/auth/user/query_by_uuid:
    get:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据uuid查询用户
      tags:
      - 用户模块
  /api/captcha/rotate/check:
    post:
      description: 验证旋转验证码
      parameters:
      - description: 验证码角度
        in: query
        name: angle
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/rotate/get:
    get:
      description: 生成旋转验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/shape/check:
    get:
      description: 生成点击形状基础验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状基础验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/get:
    get:
      description: 生成点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/check:
    get:
      description: 验证点击形状验证码
      parameters:
      - description: 点击坐标
        in: query
        name: point
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/region/get:
    get:
      description: 生成点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/text/check:
    get:
      description: 验证基础文字验证码
      parameters:
      - description: 验证码
        in: query
        name: captcha
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证基础文字验证码
      tags:
      - 基础文字验证码
  /api/captcha/text/get:
    get:
      description: 生成基础文字验证码
      parameters:
      - description: 验证码类型
        in: query
        name: type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成基础文字验证码
      tags:
      - 基础文字验证码
  /api/comment/reply:
    post:
      consumes:
      - application/json
      description: 提交回复
      parameters:
      - description: 回复评论请求
        in: body
        name: reply_comment_request
        required: true
        schema:
          $ref: '#/definitions/dto.ReplyCommentRequest'
      produces:
      - application/json
      responses: {}
      summary: 提交回复
      tags:
      - 评论
  /api/comment/submit:
    post:
      consumes:
      - application/json
      description: 提交评论
      parameters:
      - description: 评论请求
        in: body
        name: comment_request
        required: true
        schema:
          $ref: '#/definitions/dto.CommentRequest'
      produces:
      - application/json
      responses: {}
      summary: 提交评论
      tags:
      - 评论
  /api/oauth/callback_notify:
    post:
      description: 微信回调
      produces:
      - application/json
      responses: {}
      summary: 微信回调
      tags:
      - 微信公众号
  /api/oauth/callback_verify:
    get:
      description: 微信回调验证
      produces:
      - application/json
      responses: {}
      summary: 微信回调验证
      tags:
      - 微信公众号
  /api/oauth/generate_client_id:
    get:
      description: 生成客户端ID
      produces:
      - application/json
      responses: {}
      summary: 生成客户端ID
      tags:
      - 微信公众号
  /api/oauth/get_temp_qrcode:
    get:
      description: 获取临时二维码
      parameters:
      - description: 客户端ID
        in: query
        name: client_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 获取临时二维码
      tags:
      - 微信公众号
  /api/oauth/gitee/callback:
    get:
      description: 处理Gitee回调
      produces:
      - application/json
      responses: {}
      summary: 处理Gitee回调
      tags:
      - Gitee OAuth
  /api/oauth/gitee/get_url:
    get:
      description: 获取Gitee登录地址
      produces:
      - application/json
      responses:
        "200":
          description: 登录地址
          schema:
            type: string
      summary: 获取Gitee登录地址
      tags:
      - Gitee OAuth
  /api/oauth/github/callback:
    get:
      description: 登录回调函数
      parameters:
      - description: code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            type: string
      summary: 登录回调函数
      tags:
      - Github OAuth
  /api/oauth/github/get_url:
    get:
      description: 获取github登录url
      produces:
      - application/json
      responses:
        "200":
          description: 登录url
          schema:
            type: string
      summary: 获取github登录url
      tags:
      - Github OAuth
  /api/oauth/qq/callback:
    get:
      description: QQ登录回调
      produces:
      - application/json
      responses: {}
      summary: QQ登录回调
      tags:
      - QQ OAuth
  /api/oauth/qq/get_url:
    get:
      description: 获取QQ登录地址
      produces:
      - application/json
      responses:
        "200":
          description: 登录地址
          schema:
            type: string
      summary: 获取QQ登录地址
      tags:
      - QQ OAuth
  /api/sms/ali/send:
    get:
      description: 发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送短信验证码
      tags:
      - 短信验证码
  /api/sms/smsbao/send:
    get:
      description: 短信宝发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 短信宝发送短信验证码
      tags:
      - 短信验证码
  /api/sms/test/send:
    get:
      description: 发送测试短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送测试短信验证码
      tags:
      - 短信验证码
  /api/token/refresh:
    post:
      parameters:
      - description: 刷新token
        in: query
        name: refresh_token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 刷新token
      tags:
      - 用户模块
  /api/user/login:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AccountLoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 账号登录
      tags:
      - 用户模块
  /api/user/phone_login:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.PhoneLoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 手机号登录/注册
      tags:
      - 用户模块
  /api/user/reset_password:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.ResetPasswordRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 重置密码
      tags:
      - 用户模块
  /api/ws/gws:
    get:
      description: 创建websocket服务
      responses: {}
      summary: 创建websocket服务
      tags:
      - websocket
swagger: "2.0"
