definitions:
  dto.AccountLoginRequest:
    properties:
      account:
        type: string
      auto_login:
        type: boolean
      password:
        type: string
    type: object
  dto.AddUserRequest:
    properties:
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  dto.PhoneLoginRequest:
    properties:
      auto_login:
        type: boolean
      captcha:
        type: string
      phone:
        type: string
    type: object
  dto.ResetPasswordRequest:
    properties:
      captcha:
        type: string
      password:
        type: string
      phone:
        type: string
      repassword:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/user/List:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取所有用户列表
      tags:
      - 用户模块
  /api/auth/user/delete:
    delete:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
  /api/auth/user/query_by_phone:
    get:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据手机号查询用户
      tags:
      - 用户模块
  /api/auth/user/query_by_username:
    get:
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据用户名查询用户
      tags:
      - 用户模块
  /api/auth/user/query_by_uuid:
    get:
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据uuid查询用户
      tags:
      - 用户模块
  /api/captcha/rotate/check:
    post:
      description: 验证旋转验证码
      parameters:
      - description: 验证码角度
        in: query
        name: angle
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/rotate/get:
    get:
      description: 生成旋转验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成旋转验证码
      tags:
      - 旋转验证码
  /api/captcha/shape/check:
    get:
      description: 生成点击形状基础验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状基础验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/get:
    get:
      description: 生成点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/check:
    get:
      description: 验证点击形状验证码
      parameters:
      - description: 点击坐标
        in: query
        name: point
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/shape/slide/region/get:
    get:
      description: 生成点击形状验证码
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成点击形状验证码
      tags:
      - 点击形状验证码
  /api/captcha/text/check:
    get:
      description: 验证基础文字验证码
      parameters:
      - description: 验证码
        in: query
        name: captcha
        required: true
        type: string
      - description: 验证码key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 验证基础文字验证码
      tags:
      - 基础文字验证码
  /api/captcha/text/get:
    get:
      description: 生成基础文字验证码
      parameters:
      - description: 验证码类型
        in: query
        name: type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成基础文字验证码
      tags:
      - 基础文字验证码
  /api/oauth/callback_notify:
    post:
      description: 微信回调
      produces:
      - application/json
      responses: {}
      summary: 微信回调
      tags:
      - 微信公众号
  /api/oauth/callback_verify:
    get:
      description: 微信回调验证
      produces:
      - application/json
      responses: {}
      summary: 微信回调验证
      tags:
      - 微信公众号
  /api/oauth/generate_client_id:
    get:
      description: 生成客户端ID
      produces:
      - application/json
      responses: {}
      summary: 生成客户端ID
      tags:
      - 微信公众号
  /api/oauth/get_temp_qrcode:
    get:
      description: 获取临时二维码
      parameters:
      - description: 客户端ID
        in: query
        name: client_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 获取临时二维码
      tags:
      - 微信公众号
  /api/oauth/gitee/callback:
    get:
      description: 处理Gitee回调
      produces:
      - application/json
      responses: {}
      summary: 处理Gitee回调
      tags:
      - Gitee OAuth
  /api/oauth/gitee/get_url:
    get:
      description: 获取Gitee登录地址
      produces:
      - application/json
      responses:
        "200":
          description: 登录地址
          schema:
            type: string
      summary: 获取Gitee登录地址
      tags:
      - Gitee OAuth
  /api/oauth/github/callback:
    get:
      description: 登录回调函数
      parameters:
      - description: code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            type: string
      summary: 登录回调函数
      tags:
      - Github OAuth
  /api/oauth/github/get_url:
    get:
      description: 获取github登录url
      produces:
      - application/json
      responses:
        "200":
          description: 登录url
          schema:
            type: string
      summary: 获取github登录url
      tags:
      - Github OAuth
  /api/oauth/qq/callback:
    get:
      description: QQ登录回调
      produces:
      - application/json
      responses: {}
      summary: QQ登录回调
      tags:
      - QQ OAuth
  /api/oauth/qq/get_url:
    get:
      description: 获取QQ登录地址
      produces:
      - application/json
      responses:
        "200":
          description: 登录地址
          schema:
            type: string
      summary: 获取QQ登录地址
      tags:
      - QQ OAuth
  /api/sms/ali/send:
    get:
      description: 发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送短信验证码
      tags:
      - 短信验证码
  /api/sms/smsbao/send:
    get:
      description: 短信宝发送短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 短信宝发送短信验证码
      tags:
      - 短信验证码
  /api/sms/test/send:
    get:
      description: 发送测试短信验证码
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 发送测试短信验证码
      tags:
      - 短信验证码
  /api/token/refresh:
    post:
      parameters:
      - description: 刷新token
        in: query
        name: refresh_token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 刷新token
      tags:
      - 用户模块
  /api/user/add:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AddUserRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 添加用户
      tags:
      - 用户模块
  /api/user/login:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AccountLoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 账号登录
      tags:
      - 用户模块
  /api/user/phone_login:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.PhoneLoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 手机号登录/注册
      tags:
      - 用户模块
  /api/user/reset_password:
    post:
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.ResetPasswordRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 重置密码
      tags:
      - 用户模块
  /api/ws/gws:
    get:
      description: 创建websocket服务
      responses: {}
      summary: 创建websocket服务
      tags:
      - websocket
  /api/ws/socket:
    get:
      description: 创建websocket服务
      responses: {}
      summary: 创建websocket服务(gorilla)
      tags:
      - websocket
swagger: "2.0"
